# Site settings
title: EK Keramik
email: evakobel7@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Oplev unikt, håndlavet keramik fra Eva Kobels værksted i Sandager ved Assens på Fyn. Skåle, kander, tallerkner og skulpturer i enkle former og klare farver – alt drejet og brændt i eget værksted. Køb direkte fra butikken, på markeder og udstillinger, eller tilmeld dig keramikkursus med plads til kun 5 deltagere. Besøg ekkeramik.dk og find dit næste unikke stykke dansk kunsthåndværk.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Eva Kobel
email: evakobel7@gmail.com
facebook_username: eva.kobel.3
twitter_username:
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone: +45 2946 7904
copyright: Copyright (c) 2026 Eva Kobel. All rights reserved.

# API settings
google_api_key:

# Build settings
markdown: kramdown
